spring:
  application:
    name: eccto-provider
server:
  port: 8002
eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: 1.0.0
      NODE_GROUP_ID: ${ECCTO_NODE_GROUP_ID:0}
      PRODUCT_CODE: ${ECCTO_PRODUCT_CODE:DEFAULT}
      PRODUCT_VERSION_CODE: ${ECCTO_PRODUCT_VERSION_CODE:DEFAULT}
      PRODUCT_ENV_CODE: ${ECCTO_PRODUCT_ENV_CODE:DEFAULT}
      SERVICE_VERSION_CODE: ${ECCTO_SERVICE_VERSION_CODE:DEFAULT}
  client:
    serviceUrl:
      defaultZone: http://study.eccto.cn:8001/eureka
    registryFetchIntervalSeconds: 10
    disable-delta: true
