spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ericchen-vip/{application}
          #username:
          #password:
          ## 强制拉去 Git 内容
          force-pull: true
          default-label: master
          search-paths: multi-repo-demo
  application:
    name: ch12-1-config-server-placeholders
server:
    port: 8011
logging:
  level:
    root: debug
