server:
  port: 8005
management:
  server:
    port: 9005
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
      ribbon:
        enabled: false
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
