spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: method_route
          uri: lb://eccto-provider
          predicates:
           - Path=/client1/**
          filters:
             - StripPrefix=1
             - AddRequestHeader=MyRequestHeader, Bar
             - AddRequestParameter=foo, bar
             - AddResponseHeader=MyResponseHeader, hello
#        - id: method_route
#          uri: http://localhost:8002
#          predicates:
#            - Method=GET