spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug